FROM openjdk
WORKDIR usr/lib
ADD ./target/Authentication-Service-0.0.1-SNAPSHOT.jar /usr/lib/Authentication-Service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","Authentication-Service-0.0.1-SNAPSHOT.jar"]