server:
  port: 8081
  error:
    include-message: always
spring:
  cloud:
    compatibility-verifier:
      enabled: false
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/uservehicleDb}
  application:
    name: user-product-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true

