version: "3.3"
services:
  mysqlservice:
    image: mysql:5.5
    container_name: mysql-container
    network_mode: host
    ports:
      - 3306:3306
    environment:
      MYSQL_USERNAME: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"


  mongodbservice:
    image: mongo:latest
    container_name: mongo-container
    network_mode: host
    ports:
      - 27017:27017

  userauthenticationservice:
    container_name: authentication-service
    build: Authentication-Service/
    network_mode: host
    ports:
      - 8085:8085
    depends_on:
      - mysqlservice
      - cloudapiservice
      - eurekaServer
    restart: always

  productservice:
    container_name: vehicle-service
    build: Vehicle-Service/
    network_mode: host
    ports:
      - 8081:8081
    depends_on:
      - mongodbservice
      - cloudapiservice
      - eurekaServer
    restart: always

  cloudapiservice:
    image: cloud-api-service
    build: SpringCloudApiGateway/
    restart: always
    network_mode: host
    ports:
      - 9000:9000
    environment:
      API_GATEWAY_PORT: 9000
      EUREKA_SERVER_IP: localhost
      EUREKA_SERVER_PORT: 8761
    depends_on:
      - eurekaServer

  eurekaServer:
    image: eureka-service
    build: EurekaServer/
    restart: always
    network_mode: host
    #hostname: localhost
    environment:
      EUREKA_SERVER_PORT: 8761
    ports:
      - 8761:8761